# Site
repository: zhenming91/cv
favicon: images/favicon.ico

# Personal info
name: Zhen Ming Ng
title: Machine Learning Full-stack engineer
email: zhenming91@hotmail.com

# Social links
# twitter_username: facespics
github_username:  sabi-wabi
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: zhenming91
linkedin_username: zhen-ming-ng-b312aa99
# pinterest_username: jekyll
youtube_username: TheZhenMing
# googleplus_username: +jekyll

# About Section
about_title: About Me
about_profile_image: images/me.JPG
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Ming and I am a full-stack developer with an engineering background and practical experience in the oil and gas industry. 

  I am a pragmatic engineer that does what needs to be done to deliver exceptional work.

  I am self-motivated, self-taught and self-managed.

  Programming languages : <mark> R </mark> , <mark> Python </mark> , <mark> SQL </mark> , <mark> JavaScript </mark>, <mark> HTML </mark> , <mark> CSS </mark> 
  Frameworks : <mark>React JS</mark>,<mark>Next JS</mark>,<mark>NoSQL</mark>,,<mark>Docker</mark>,,<mark>Apache Spark</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: My own perception about myself as a person
more_content: | # this will include new lines to allow paragraphs

   - <mark>Introvert</mark> who is only ever comfortable in non-small talks. Weak in formal talks.
   - <mark>Hardworking</mark> who willingly put effort as long as it interests me
   - <mark>Direct</mark> who does not like to sacrifice clarity for the sake of politeness
   - <mark>Calculative</mark> who overthinks with the intention to make the most of every situation 
   - <mark>Single minded</mark> who is stubborn to absorb other people's views if not reasonably grounded 
   - <mark>Impatient</mark> who is eager to get things done fast
   - <mark>Efficiency is king</mark> who dislike bureaucratic processes



# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
